language: php
php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"


addons:
  hosts:
    - mongodb-container

services:
  - docker

before_install:
  - docker run --name mongodb-container --rm -e TZ=America/Winnipeg -p 27017:27017 -d mongo:3
  - docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=aaa" -e "MINIO_SECRET_KEY=12345678" -d minio/minio server /data
  - docker run -p 8000:8000 -d amazon/dynamodb-local
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export S3_CONNECTION="s3://aaa:12345678@us-east-1/mybucket?create=true&endpoint=http://127.0.0.1:9000"
  - export DYNAMODB_CONNECTION="dynamodb://access_key:secret_key@us-east-1/tablename?endpoint=http://127.0.0.1:8000"

install:
  - php -i
  - composer install

script:
  - vendor/bin/phpunit testsdb/MongoDbDriverTest.php
  - vendor/bin/phpunit testsdb/AwsDynamoDbDriverTest.php
  - vendor/bin/phpunit testsdb/AwsS3DriverTest.php
