language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"


addons:
  hosts:
    - mongodb-container

services:
  - docker

before_install:
  - npm install
  - node_modules/.bin/usdocker --refresh
  - node_modules/.bin/usdocker --no-link mongodb up
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


install:
  - php -i
  - composer install

script:
  - vendor/bin/phpunit testsdb/MongoDbDriverTest.php
  - vendor/bin/phpunit testsdb/AwsDynamoDbDriverTest.php
  - vendor/bin/phpunit testsdb/AwsS3DriverTest.php
