version: '2.0'
services:

  mongodb:
    container_name: anydataset_nosql_mongodb
    image: mongo:3
    environment:
      TZ: America/Winnipeg
    ports:
      - 27017:27017

  dynanodb:
    container_name: anydataset_nosql_dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  s3:
    container_name: anydataset_nosql_s3
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: aaa
      MINIO_SECRET_KEY: 12345678
    command: ["server", "/data"]
    ports:
      - 9000:9000
