name: PHPUnit
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'byjg/php:${{ matrix.php-version }}-cli'
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.0"
          - "7.4"
          - "7.3"
          - "7.2"

    services:
      mongodb:
        image: mongo:3
        env:
          TZ: America/Winnipeg
        ports:
          - 27017:27017

      dynanodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

      s3:
        image: minio/minio
        env:
          MINIO_ROOT_USER: aaa
          MINIO_ROOT_PASSWORD: 12345678
        options: |
          --entrypoint "bash -c 'minio server /data'"
        ports:
          - 9000:9000

    env:
      MONGODB_CONNECTION: "mongodb://127.0.0.1/test"
      S3_CONNECTION: "s3://aaa:12345678@us-east-1/mybucket?create=true&endpoint=http://127.0.0.1:9000"
      DYNAMODB_CONNECTION: "dynamodb://access_key:secret_key@us-east-1/tablename?endpoint=http://127.0.0.1:8000"

    steps:
      - uses: actions/checkout@v3
      - run: composer install
      - run: ./vendor/bin/phpunit

  Documentation:
    runs-on: 'ubuntu-latest'
    needs: Build
    if: github.ref == 'refs/heads/master'
    env:
      DOC_GITHUB_TOKEN: '${{ secrets.DOC_TOKEN }}'
    steps:
      - uses: actions/checkout@v3
      - run: curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin php anydataset-db
